// 游戏核心数据结构和逻辑

// 属性克制关系
const typeEffectiveness = {
    water: { fire: 2, wood: 0.5, earth: 1, water: 0.5, light: 1, dark: 1 },
    fire: { wood: 2, earth: 0.5, water: 1, fire: 0.5, light: 1, dark: 1 },
    wood: { earth: 2, water: 0.5, fire: 1, wood: 0.5, light: 1, dark: 1 },
    earth: { water: 2, fire: 0.5, wood: 1, earth: 0.5, light: 1, dark: 1 },
    light: { light: 0.5, dark: 0.5, fire: 1, water: 1, earth: 1, wood: 1 },
    dark: { light: 0.5, dark: 0.5, fire: 1, water: 1, earth: 1, wood: 1 },
    none: { fire: 1, water: 1, earth: 1, wood: 1, light: 1, dark: 1 }
};

// 内置技能模板
const skillTemplates = [
    { id: 1, name: "火焰冲击", type: "fire", power: 40, manaCost: 20, description: "发射一团火焰攻击敌人" },
    { id: 2, name: "水枪术", type: "water", power: 35, manaCost: 15, description: "喷射高压水流攻击敌人" },
    { id: 3, name: "大地之力", type: "earth", power: 45, manaCost: 25, description: "召唤大地力量攻击敌人" },
    { id: 4, name: "森林祝福", type: "wood", power: 30, manaCost: 15, description: "借助森林力量恢复生命值", heal: 25 },
    { id: 5, name: "烈焰风暴", type: "fire", power: 60, manaCost: 40, description: "召唤烈焰风暴攻击敌人" },
    { id: 6, name: "激流勇进", type: "water", power: 55, manaCost: 35, description: "释放强大水流攻击敌人" },
    { id: 7, name: "圣光术", type: "light", power: 35, manaCost: 20, description: "释放圣洁光芒攻击敌人并恢复少量生命", heal: 15 },
    { id: 8, name: "暗影突袭", type: "dark", power: 50, manaCost: 30, description: "利用暗影之力突袭敌人" },
    { id: 9, name: "光明治愈", type: "light", power: 0, manaCost: 25, description: "强大的治疗技能，恢复大量生命值", heal: 50 },
    { id: 10, name: "黑暗诅咒", type: "dark", power: 25, manaCost: 35, description: "诅咒敌人，使其每回合受到持续伤害", dot: 10, dotDuration: 3 },
    { id: 11, name: "雷电术", type: "water", power: 45, manaCost: 25, description: "召唤雷电攻击敌人" },
    { id: 12, name: "熔岩喷发", type: "fire", power: 55, manaCost: 35, description: "释放高温熔岩攻击敌人" },
    { id: 13, name: "荆棘术", type: "wood", power: 30, manaCost: 20, description: "召唤荆棘攻击敌人并反弹部分伤害", reflect: 0.3 },
    { id: 14, name: "石化凝视", type: "earth", power: 25, manaCost: 30, description: "石化敌人，使其下回合无法行动", stun: 1 },
    { id: 15, name: "净化之光", type: "light", power: 40, manaCost: 30, description: "净化邪恶，对暗属性敌人造成额外伤害", bonus: { type: "dark", multiplier: 1.5 } },
    { id: 16, name: "吞噬暗影", type: "dark", power: 35, manaCost: 25, description: "吞噬暗影，根据造成伤害回复生命值", lifesteal: 0.3 },
    { id: 17, name: "冰霜之环", type: "water", power: 50, manaCost: 30, description: "释放冰霜之力，对周围敌人造成伤害并减速" },
    { id: 18, name: "火焰之墙", type: "fire", power: 45, manaCost: 35, description: "召唤火焰之墙，对穿过敌人造成伤害" },
    { id: 19, name: "大地护盾", type: "earth", power: 0, manaCost: 25, description: "召唤大地护盾，减少下次受到的伤害", shield: 0.5 },
    { id: 20, name: "自然之力", type: "wood", power: 0, manaCost: 20, description: "召唤自然之力，回复自己和队友生命值", teamHeal: 20 },
    { id: 21, name: "神圣光辉", type: "light", power: 40, manaCost: 30, description: "释放神圣光辉，驱散负面效果并造成伤害" },
    { id: 22, name: "暗影之刃", type: "dark", power: 55, manaCost: 35, description: "投掷暗影之刃，必定暴击" },
    { id: 23, name: "风暴之眼", type: "water", power: 60, manaCost: 40, description: "召唤风暴之眼，对所有敌人造成伤害" },
    { id: 24, name: "烈焰爆裂", type: "fire", power: 50, manaCost: 30, description: "释放烈焰爆裂，对敌人造成伤害并附加燃烧效果", dot: 8, dotDuration: 2 },
    { id: 25, name: "巨石冲击", type: "earth", power: 55, manaCost: 35, description: "投掷巨石冲击敌人，有概率造成眩晕效果", stun: 1 },
    { id: 26, name: "生命之种", type: "wood", power: 0, manaCost: 25, description: "种下生命之种，每回合回复生命值", heal: 15, dotDuration: 3 },
    { id: 27, name: "天堂之门", type: "light", power: 0, manaCost: 40, description: "打开天堂之门，复活一名死亡队友", revive: true },
    { id: 28, name: "地狱烈火", type: "dark", power: 65, manaCost: 45, description: "释放地狱烈火，对敌人造成巨额伤害但会消耗自身生命值", selfDamage: 10 },
    { id: 29, name: "星辰坠落", type: "none", power: 70, manaCost: 50, description: "召唤星辰之力，无视属性克制造成伤害" },
    { id: 30, name: "时间停止", type: "none", power: 0, manaCost: 60, description: "停止时间，使敌人下三回合无法行动", stun: 3 },
    { id: 31, name: "空间撕裂", type: "none", power: 75, manaCost: 55, description: "撕裂空间，对敌人造成巨额伤害" },
    { id: 32, name: "元素融合", type: "none", power: 60, manaCost: 45, description: "融合多种元素，根据敌人属性选择最优攻击方式" },
    // 新增技能
    { id: 33, name: "爆炎弹", type: "fire", power: 75, manaCost: 45, description: "发射高爆炎弹，对敌人造成巨大火焰伤害" },
    { id: 34, name: "熔岩护甲", type: "fire", power: 0, manaCost: 30, description: "形成熔岩护甲，减少受到的伤害并反弹部分伤害", reflect: 0.25 },
    { id: 35, name: "潮汐冲击", type: "water", power: 65, manaCost: 40, description: "召唤强大的潮汐冲击敌人" },
    { id: 36, name: "寒冰屏障", type: "water", power: 0, manaCost: 35, description: "制造寒冰屏障，免疫下一次攻击", shield: 1 },
    { id: 37, name: "地震波", type: "earth", power: 70, manaCost: 45, description: "释放强烈地震波，对敌人造成伤害并降低其防御力" },
    { id: 38, name: "岩石傀儡", type: "earth", power: 0, manaCost: 50, description: "召唤岩石傀儡，分担一定比例的伤害", shield: 0.4 },
    { id: 39, name: "藤蔓缠绕", type: "wood", power: 55, manaCost: 35, description: "操控藤蔓缠绕敌人，造成伤害并限制其行动", stun: 1 },
    { id: 40, name: "古树庇护", type: "wood", power: 0, manaCost: 40, description: "召唤古树庇护，持续回复所有队友生命值", teamHeal: 15, dotDuration: 3 },
    { id: 41, name: "光辉之刃", type: "light", power: 60, manaCost: 35, description: "凝聚光之力形成利刃，对敌人造成伤害并驱散其增益效果" },
    { id: 42, name: "圣光领域", type: "light", power: 0, manaCost: 45, description: "展开圣光领域，持续净化所有负面效果并增强治疗效果", purge: true },
    { id: 43, name: "暗影束缚", type: "dark", power: 50, manaCost: 35, description: "释放暗影束缚敌人，造成伤害并附加诅咒效果", dot: 12, dotDuration: 2 },
    { id: 44, name: "恐惧光环", type: "dark", power: 0, manaCost: 40, description: "释放恐惧光环，降低敌人攻击力和防御力" },
    { id: 45, name: "虚无之触", type: "none", power: 80, manaCost: 60, description: "使用虚无之力攻击敌人，无视一切防御和属性克制" },
    { id: 46, name: "混沌领域", type: "none", power: 0, manaCost: 55, description: "展开混沌领域，使所有攻击都变为无属性并获得额外暴击率", bonus: { type: "none", multiplier: 1.3 } },
    // 再新增技能
    { id: 47, name: "烈焰漩涡", type: "fire", power: 80, manaCost: 50, description: "制造烈焰漩涡，对敌人造成持续伤害", dot: 15, dotDuration: 2 },
    { id: 48, name: "火焰护盾", type: "fire", power: 0, manaCost: 35, description: "形成火焰护盾，反弹部分伤害并灼烧攻击者", reflect: 0.3 },
    { id: 49, name: "洪水滔天", type: "water", power: 75, manaCost: 45, description: "召唤滔天洪水，对敌人造成巨额水属性伤害" },
    { id: 50, name: "冰霜之矛", type: "water", power: 65, manaCost: 40, description: "投掷冰霜之矛，对敌人造成伤害并减速", stun: 1 },
    { id: 51, name: "山崩地裂", type: "earth", power: 85, manaCost: 50, description: "引发山崩地裂，对敌人造成巨额伤害并附加流血效果" },
    { id: 52, name: "石肤术", type: "earth", power: 0, manaCost: 30, description: "强化皮肤如岩石般坚硬，减少受到的伤害", shield: 0.5 },
    { id: 53, name: "森林之怒", type: "wood", power: 70, manaCost: 45, description: "召唤森林之怒，对敌人造成伤害并回复自身生命值", heal: 25 },
    { id: 54, name: "生命汲取", type: "wood", power: 55, manaCost: 35, description: "汲取敌人生命值回复自身", lifesteal: 0.4 },
    { id: 55, name: "神圣审判", type: "light", power: 75, manaCost: 50, description: "召唤神圣审判，对敌人造成巨额伤害并驱散其增益效果" },
    { id: 56, name: "光明护盾", type: "light", power: 0, manaCost: 40, description: "形成光明护盾，免疫负面效果并持续回复生命值", shield: 0.3 },
    { id: 57, name: "暗影之球", type: "dark", power: 70, manaCost: 45, description: "凝聚暗影之力形成能量球，对敌人造成巨额伤害" },
    { id: 58, name: "诅咒之触", type: "dark", power: 0, manaCost: 35, description: "诅咒敌人，使其每回合受到持续伤害并降低属性", dot: 10, dotDuration: 3 },
    { id: 59, name: "虚空撕裂", type: "none", power: 90, manaCost: 65, description: "撕裂虚空，对敌人造成毁灭性伤害" },
    { id: 60, name: "维度扭曲", type: "none", power: 0, manaCost: 60, description: "扭曲维度，使所有攻击都无视防御", bonus: { type: "none", multiplier: 1.5 } },
    // 再新增5个技能
    { id: 61, name: "地狱火球", type: "fire", power: 90, manaCost: 55, description: "释放地狱火球，对敌人造成巨额火焰伤害并附加燃烧效果", dot: 12, dotDuration: 3 },
    { id: 62, name: "熔岩喷射", type: "fire", power: 75, manaCost: 45, description: "喷射高温熔岩，对敌人造成伤害并降低其防御力" },
    { id: 63, name: "海啸冲击", type: "water", power: 85, manaCost: 50, description: "释放海啸冲击，对敌人造成巨额水属性伤害并附加减速效果" },
    { id: 64, name: "寒冰牢笼", type: "water", power: 60, manaCost: 40, description: "制造寒冰牢笼困住敌人，使其下两回合无法行动", stun: 2 },
    { id: 65, name: "地震连击", type: "earth", power: 95, manaCost: 55, description: "连续引发地震，对敌人造成多次伤害并附加眩晕效果", stun: 1 },
    { id: 66, name: "岩石壁垒", type: "earth", power: 0, manaCost: 35, description: "构筑岩石壁垒，大幅减少受到的伤害", shield: 0.6 },
    { id: 67, name: "荆棘领域", type: "wood", power: 65, manaCost: 40, description: "展开荆棘领域，对敌人造成伤害并反弹部分伤害", reflect: 0.25 },
    { id: 68, name: "生命绽放", type: "wood", power: 0, manaCost: 45, description: "释放生命之力，持续回复所有队友生命值", teamHeal: 20, dotDuration: 4 },
    { id: 69, name: "神圣新星", type: "light", power: 80, manaCost: 50, description: "释放神圣新星，对敌人造成巨额光属性伤害并驱散其所有增益效果" },
    { id: 70, name: "光明结界", type: "light", power: 0, manaCost: 45, description: "展开光明结界，免疫所有负面效果并持续回复生命值和魔法值", shield: 0.4 },
    { id: 71, name: "暗影风暴", type: "dark", power: 85, manaCost: 50, description: "释放暗影风暴，对敌人造成巨额暗属性伤害并附加诅咒效果" },
    { id: 72, name: "恐惧之云", type: "dark", power: 0, manaCost: 40, description: "释放恐惧之云，降低所有敌人攻击力和防御力" },
    { id: 73, name: "虚空之刃", type: "none", power: 100, manaCost: 70, description: "凝聚虚空之力形成利刃，对敌人造成毁灭性伤害" },
    { id: 74, name: "混沌之触", type: "none", power: 0, manaCost: 65, description: "释放混沌之触，使敌人下三回合所有属性攻击都变为无属性", bonus: { type: "none", multiplier: 1.2 } },
    // 再新增10个技能
    { id: 75, name: "烈焰龙息", type: "fire", power: 95, manaCost: 60, description: "释放烈焰龙息，对敌人造成巨额火焰伤害并附加燃烧效果", dot: 15, dotDuration: 3 },
    { id: 76, name: "熔岩爆发", type: "fire", power: 85, manaCost: 50, description: "引发熔岩爆发，对敌人造成伤害并反弹部分伤害", reflect: 0.2 },
    { id: 77, name: "暴雨连击", type: "water", power: 90, manaCost: 55, description: "释放暴雨连击，对敌人造成多次水属性伤害" },
    { id: 78, name: "冰封千里", type: "water", power: 75, manaCost: 45, description: "释放极寒之力，冻结所有敌人并造成巨额伤害", stun: 2 },
    { id: 79, name: "大地震击", type: "earth", power: 100, manaCost: 60, description: "释放强烈地震，对敌人造成巨额伤害并附加眩晕和流血效果", stun: 1 },
    { id: 80, name: "石化领域", type: "earth", power: 0, manaCost: 40, description: "展开石化领域，使敌人有概率被石化", stun: 1 },
    { id: 81, name: "森林复苏", type: "wood", power: 0, manaCost: 50, description: "唤醒森林之力，立即复活所有死亡队友并回复全部生命值", revive: true },
    { id: 82, name: "荆棘囚笼", type: "wood", power: 75, manaCost: 50, description: "展开荆棘囚笼，对敌人造成巨额伤害并反弹部分伤害", reflect: 0.3 },
    { id: 83, name: "神圣制裁", type: "light", power: 90, manaCost: 55, description: "执行神圣制裁，对敌人造成巨额光属性伤害并净化所有负面效果", purge: true },
    { id: 84, name: "光明洗礼", type: "light", power: 0, manaCost: 50, description: "释放光明洗礼，免疫所有伤害和负面效果并持续回复所有队友", teamHeal: 25, shield: 2 },
    { id: 85, name: "暗影军团", type: "dark", power: 95, manaCost: 55, description: "召唤暗影军团，对敌人造成巨额暗属性伤害并附加多个负面效果" },
    { id: 86, name: "恐惧领域", type: "dark", power: 0, manaCost: 45, description: "展开恐惧领域，降低所有敌人攻击力和防御力" },
    { id: 87, name: "虚空风暴", type: "none", power: 110, manaCost: 75, description: "释放虚空风暴，对敌人造成毁灭性伤害" },
    { id: 88, name: "混沌漩涡", type: "none", power: 0, manaCost: 70, description: "展开混沌漩涡，使敌人下三回合所有攻击都变为无属性", bonus: { type: "none", multiplier: 1.4 } },
    { id: 89, name: "星辰爆裂", type: "none", power: 105, manaCost: 70, description: "引发星辰爆裂，对敌人造成巨额伤害并附加眩晕效果", stun: 1 },
    { id: 90, name: "时空扭曲", type: "none", power: 0, manaCost: 75, description: "扭曲时空，使敌人下四回合无法行动", stun: 2 }
];

// 内置被动技能模板
const passiveTemplates = [
    { id: 1, name: "坚韧", type: "earth", description: "受到伤害时减少10%伤害" },
    { id: 2, name: "敏捷", type: "wood", description: "攻击速度提升15%" },
    { id: 3, name: "法力涌动", type: "water", description: "每回合回复5点魔法值" },
    { id: 4, name: "暴击", type: "fire", description: "暴击率提升10%" },
    { id: 5, name: "圣光庇护", type: "light", description: "受到致命伤害时有20%概率免死" },
    { id: 6, name: "暗影步", type: "dark", description: "闪避率提升10%" },
    { id: 7, name: "雷鸣", type: "water", description: "攻击时有15%概率造成额外雷电伤害" },
    { id: 8, name: "火焰强化", type: "fire", description: "火属性技能伤害提升10%" },
    { id: 9, name: "大地之盾", type: "earth", description: "受到暴击伤害时减少20%" },
    { id: 10, name: "自然之力", type: "wood", description: "每回合回复2%最大生命值" },
    { id: 11, name: "寒冰护体", type: "water", description: "受到攻击时有15%概率冻结攻击者" },
    { id: 12, name: "熔岩之躯", type: "fire", description: "受到物理攻击时反弹10%伤害" },
    { id: 13, name: "岩石皮肤", type: "earth", description: "受到伤害时有20%概率减少一半伤害" },
    { id: 14, name: "生命汲取", type: "wood", description: "攻击时回复造成伤害5%的生命值" },
    { id: 15, name: "光明祝福", type: "light", description: "所有治疗效果提升15%" },
    { id: 16, name: "暗影帷幕", type: "dark", description: "受到单体攻击时有10%概率完全闪避" },
    { id: 17, name: "风暴之眼", type: "water", description: "暴击伤害提升20%" },
    { id: 18, name: "烈焰之心", type: "fire", description: "每回合回复1%最大生命值" },
    { id: 19, name: "大地之力", type: "earth", description: "防御力提升10%" },
    { id: 20, name: "森林之魂", type: "wood", description: "受到致命伤害时有15%概率恢复30%生命值" },
    { id: 21, name: "神圣光环", type: "light", description: "每回合回复2点魔法值" },
    { id: 22, name: "暗影之拥", type: "dark", description: "攻击时有10%概率附加诅咒效果" },
    { id: 23, name: "星辰之力", type: "none", description: "所有技能无视属性克制" },
    { id: 24, name: "时间回溯", type: "none", description: "每场战斗开始时获得一次复活机会" },
    { id: 25, name: "空间稳定", type: "none", description: "免疫所有控制效果" },
    { id: 26, name: "元素亲和", type: "none", description: "所有属性技能伤害提升15%" },
    // 新增被动技能
    { id: 27, name: "烈焰精通", type: "fire", description: "火属性技能暴击率提升15%" },
    { id: 28, name: "熔岩核心", type: "fire", description: "每回合回复3点魔法值，火属性技能伤害提升8%" },
    { id: 29, name: "潮汐掌握", type: "water", description: "水属性技能有20%概率不消耗魔法值" },
    { id: 30, name: "深海之力", type: "water", description: "受到伤害时回复3点魔法值" },
    { id: 31, name: "山岳守护", type: "earth", description: "受到暴击时减少30%伤害" },
    { id: 32, name: "大地共鸣", type: "earth", description: "每回合回复1%最大生命值和魔法值" },
    { id: 33, name: "森林庇护", type: "wood", description: "每场战斗开始时获得相当于最大生命值10%的护盾" },
    { id: 34, name: "自然协调", type: "wood", description: "治疗技能效果提升20%" },
    { id: 35, name: "光辉祝福", type: "light", description: "光属性技能有15%概率造成双倍伤害" },
    { id: 36, name: "圣光洗礼", type: "light", description: "每回合净化一个负面效果" },
    { id: 37, name: "暗影精通", type: "dark", description: "暗属性技能有20%概率附加流血效果" },
    { id: 38, name: "恐惧光环", type: "dark", description: "攻击时有10%概率降低敌人10%攻击力" },
    { id: 39, name: "虚无掌握", type: "none", description: "所有技能暴击伤害提升25%" },
    { id: 40, name: "混沌之力", type: "none", description: "每回合获得1点额外怒气" },
    // 再新增被动技能
    { id: 41, name: "爆炎之心", type: "fire", description: "暴击时附加燃烧效果" },
    { id: 42, name: "熔岩护体", type: "fire", description: "受到攻击时有15%概率反弹伤害" },
    { id: 43, name: "海神祝福", type: "water", description: "每回合回复2点魔法值和生命值" },
    { id: 44, name: "潮汐之力", type: "water", description: "暴击伤害提升25%" },
    { id: 45, name: "山崩守护", type: "earth", description: "受到致命伤害时减少40%伤害" },
    { id: 46, name: "岩石之心", type: "earth", description: "每回合回复1%最大生命值" },
    { id: 47, name: "丛林之魂", type: "wood", description: "每场战斗开始时回复10%生命值" },
    { id: 48, name: "生命链接", type: "wood", description: "攻击时回复造成伤害3%的生命值" },
    { id: 49, name: "神圣意志", type: "light", description: "免疫一次负面效果" },
    { id: 50, name: "光明之心", type: "light", description: "每回合回复3点魔法值" },
    { id: 51, name: "暗影之魂", type: "dark", description: "暴击时回复造成伤害10%的生命值" },
    { id: 52, name: "恐惧之触", type: "dark", description: "攻击时有15%概率使敌人下回合攻击力降低" },
    { id: 53, name: "虚空之心", type: "none", description: "所有技能暴击率提升10%" },
    { id: 54, name: "混沌护盾", type: "none", description: "每场战斗开始时获得相当于最大生命值15%的护盾" },
    // 再新增5个被动技能
    { id: 55, name: "烈焰之魂", type: "fire", description: "每回合回复2%最大生命值，火属性技能伤害提升12%" },
    { id: 56, name: "熔岩之心", type: "fire", description: "受到致命伤害时有20%概率免死并回复30%生命值" },
    { id: 57, name: "海神之力", type: "water", description: "每回合回复3点魔法值，水属性技能暴击伤害提升20%" },
    { id: 58, name: "深海守护", type: "water", description: "受到暴击时减少25%伤害并回复5点魔法值" },
    { id: 59, name: "大地之魂", type: "earth", description: "每回合回复1%最大生命值和魔法值，受到伤害时有15%概率减少一半伤害" },
    { id: 60, name: "岩石壁垒", type: "earth", description: "受到攻击时有20%概率获得护盾" },
    { id: 61, name: "森林之心", type: "wood", description: "每回合回复2%最大生命值，治疗技能效果提升15%" },
    { id: 62, name: "自然守护", type: "wood", description: "受到致命伤害时有15%概率恢复50%生命值" },
    { id: 63, name: "神圣之魂", type: "light", description: "每回合回复2点魔法值，光属性技能有10%概率造成双倍伤害" },
    { id: 64, name: "光明守护", type: "light", description: "免疫一次负面效果，每场战斗开始时获得护盾" },
    { id: 65, name: "暗影之魂", type: "dark", description: "每回合回复2点魔法值，暗属性技能有15%概率附加流血效果" },
    { id: 66, name: "恐惧之心", type: "dark", description: "攻击时有10%概率降低敌人15%攻击力和防御力" },
    { id: 67, name: "虚空之魂", type: "none", description: "所有技能无视防御，暴击伤害提升30%" },
    { id: 68, name: "混沌之心", type: "none", description: "每回合获得2点额外怒气，所有技能伤害提升10%" },
    // 再新增10个被动技能
    { id: 69, name: "烈焰领域", type: "fire", description: "每回合回复3%最大生命值，火属性技能暴击率提升20%" },
    { id: 70, name: "熔岩神魂", type: "fire", description: "受到致命伤害时有25%概率免死并回复50%生命值" },
    { id: 71, name: "海神祝福", type: "water", description: "每回合回复4点魔法值和生命值，水属性技能有25%概率不消耗魔法值" },
    { id: 72, name: "深海神力", type: "water", description: "受到暴击时减少30%伤害并回复8点魔法值" },
    { id: 73, name: "大地神魂", type: "earth", description: "每回合回复2%最大生命值和魔法值，受到伤害时有20%概率减少一半伤害" },
    { id: 74, name: "岩石神盾", type: "earth", description: "受到攻击时有25%概率获得护盾" },
    { id: 75, name: "森林神心", type: "wood", description: "每回合回复3%最大生命值，治疗技能效果提升20%" },
    { id: 76, name: "自然神佑", type: "wood", description: "受到致命伤害时有20%概率恢复70%生命值" },
    { id: 77, name: "神圣神魂", type: "light", description: "每回合回复3点魔法值，光属性技能有15%概率造成双倍伤害" },
    { id: 78, name: "光明神佑", type: "light", description: "免疫一次负面效果，每场战斗开始时获得相当于最大生命值20%的护盾" },
    { id: 79, name: "暗影神魂", type: "dark", description: "每回合回复3点魔法值，暗属性技能有20%概率附加流血效果" },
    { id: 80, name: "恐惧神力", type: "dark", description: "攻击时有15%概率降低敌人20%攻击力和防御力" },
    { id: 81, name: "虚空神魂", type: "none", description: "所有技能无视防御和属性克制，暴击伤害提升35%" },
    { id: 82, name: "混沌神心", type: "none", description: "每回合获得3点额外怒气，所有技能伤害提升15%" }
];

// 内置自动回蓝机制模板
const manaRegenTemplates = [
    { id: 1, name: "自然恢复", type: "wood", rate: 3, description: "每回合回复3点魔法值" },
    { id: 2, name: "冥想", type: "water", rate: 5, description: "每回合回复5点魔法值" },
    { id: 3, name: "能量核心", type: "fire", rate: 7, description: "每回合回复7点魔法值" },
    { id: 4, name: "光之源泉", type: "light", rate: 4, description: "每回合回复4点魔法值并回复1点生命值" },
    { id: 5, name: "暗能汲取", type: "dark", rate: 6, description: "每回合回复6点魔法值" },
    { id: 6, name: "风暴之力", type: "water", rate: 5, description: "每回合回复5点魔法值，暴击率提升5%" },
    { id: 7, name: "熔岩之心", type: "fire", rate: 6, description: "每回合回复6点魔法值，火属性技能伤害提升5%" },
    { id: 8, name: "冰霜之心", type: "water", rate: 7, description: "每回合回复7点魔法值，受到伤害时有10%概率回复额外魔法值" },
    { id: 9, name: "大地核心", type: "earth", rate: 6, description: "每回合回复6点魔法值，受到暴击时回复额外魔法值" },
    { id: 10, name: "森林之心", type: "wood", rate: 5, description: "每回合回复5点魔法值，每回合回复1%最大生命值" },
    { id: 11, name: "光明之源", type: "light", rate: 5, description: "每回合回复5点魔法值，受到治疗效果提升10%" },
    { id: 12, name: "暗影之源", type: "dark", rate: 7, description: "每回合回复7点魔法值，攻击时有10%概率回复额外魔法值" },
    { id: 13, name: "风暴核心", type: "water", rate: 6, description: "每回合回复6点魔法值，暴击伤害提升15%" },
    { id: 14, name: "熔岩核心", type: "fire", rate: 7, description: "每回合回复7点魔法值，受到攻击时回复额外魔法值" },
    { id: 15, name: "星辰回响", type: "none", rate: 8, description: "每回合回复8点魔法值，所有技能伤害提升5%" },
    { id: 16, name: "时间流速", type: "none", rate: 6, description: "每回合回复6点魔法值，回合开始时额外回复2点魔法值" },
    { id: 17, name: "空间节点", type: "none", rate: 7, description: "每回合回复7点魔法值，受到伤害时有15%概率回复额外魔法值" },
    { id: 18, name: "元素循环", type: "none", rate: 9, description: "每回合回复9点魔法值，使用技能后有20%概率不消耗魔法值" },
    // 新增回蓝机制
    { id: 19, name: "烈焰回响", type: "fire", rate: 8, description: "每回合回复8点魔法值，火属性技能伤害提升10%" },
    { id: 20, name: "熔岩共鸣", type: "fire", rate: 7, description: "每回合回复7点魔法值，受到攻击时回复3点魔法值" },
    { id: 21, name: "潮汐之力", type: "water", rate: 8, description: "每回合回复8点魔法值，暴击率提升8%" },
    { id: 22, name: "深海源泉", type: "water", rate: 6, description: "每回合回复6点魔法值，每回合回复1%最大生命值" },
    { id: 23, name: "大地脉动", type: "earth", rate: 7, description: "每回合回复7点魔法值，受到暴击时回复5点魔法值" },
    { id: 24, name: "岩石之心", type: "earth", rate: 6, description: "每回合回复6点魔法值，每回合回复2点生命值" },
    { id: 25, name: "森林回响", type: "wood", rate: 6, description: "每回合回复6点魔法值，治疗效果提升15%" },
    { id: 26, name: "生命之泉", type: "wood", rate: 5, description: "每回合回复5点魔法值，每回合回复2%最大生命值" },
    { id: 27, name: "光辉回响", type: "light", rate: 6, description: "每回合回复6点魔法值，净化一个负面效果" },
    { id: 28, name: "圣光源泉", type: "light", rate: 5, description: "每回合回复5点魔法值，受到治疗效果提升20%" },
    { id: 29, name: "暗影回响", type: "dark", rate: 7, description: "每回合回复7点魔法值，攻击时有15%概率回复额外魔法值" },
    { id: 30, name: "虚空源泉", type: "dark", rate: 8, description: "每回合回复8点魔法值，暴击伤害提升10%" },
    { id: 31, name: "虚无回响", type: "none", rate: 9, description: "每回合回复9点魔法值，所有技能暴击率提升5%" },
    { id: 32, name: "混沌源泉", type: "none", rate: 10, description: "每回合回复10点魔法值，使用技能后有25%概率不消耗魔法值" },
    // 再新增回蓝机制
    { id: 33, name: "爆炎回响", type: "fire", rate: 9, description: "每回合回复9点魔法值，暴击时回复额外魔法值" },
    { id: 34, name: "熔岩之心", type: "fire", rate: 8, description: "每回合回复8点魔法值，受到伤害时回复4点魔法值" },
    { id: 35, name: "海神之力", type: "water", rate: 9, description: "每回合回复9点魔法值，每回合回复2%最大生命值" },
    { id: 36, name: "潮汐源泉", type: "water", rate: 7, description: "每回合回复7点魔法值，暴击伤害提升20%" },
    { id: 37, name: "大地回响", type: "earth", rate: 8, description: "每回合回复8点魔法值，受到暴击时回复6点魔法值" },
    { id: 38, name: "山岳之心", type: "earth", rate: 7, description: "每回合回复7点魔法值，每回合回复1%最大生命值和魔法值" },
    { id: 39, name: "森林之心", type: "wood", rate: 7, description: "每回合回复7点魔法值，每回合回复3%最大生命值" },
    { id: 40, name: "自然源泉", type: "wood", rate: 6, description: "每回合回复6点魔法值，治疗效果提升25%" },
    { id: 41, name: "光辉之心", type: "light", rate: 7, description: "每回合回复7点魔法值，净化所有负面效果" },
    { id: 42, name: "圣光回响", type: "light", rate: 6, description: "每回合回复6点魔法值，受到治疗效果提升25%" },
    { id: 43, name: "暗影之心", type: "dark", rate: 8, description: "每回合回复8点魔法值，攻击时回复造成伤害2%的生命值" },
    { id: 44, name: "虚空回响", type: "dark", rate: 9, description: "每回合回复9点魔法值，暴击率提升12%" },
    { id: 45, name: "虚无之心", type: "none", rate: 10, description: "每回合回复10点魔法值，所有技能无视防御" },
    { id: 46, name: "混沌之心", type: "none", rate: 11, description: "每回合回复11点魔法值，使用技能后有30%概率不消耗魔法值" },
    // 再新增5个回蓝机制
    { id: 47, name: "地狱回响", type: "fire", rate: 10, description: "每回合回复10点魔法值，暴击时回复额外生命值" },
    { id: 48, name: "熔岩之魂", type: "fire", rate: 9, description: "每回合回复9点魔法值，受到致命伤害时回复5点魔法值" },
    { id: 49, name: "海神祝福", type: "water", rate: 10, description: "每回合回复10点魔法值，每回合回复3%最大生命值" },
    { id: 50, name: "深海之心", type: "water", rate: 8, description: "每回合回复8点魔法值，暴击伤害提升25%" },
    { id: 51, name: "大地祝福", type: "earth", rate: 9, description: "每回合回复9点魔法值，受到暴击时回复8点魔法值和生命值" },
    { id: 52, name: "岩石之魂", type: "earth", rate: 8, description: "每回合回复8点魔法值，每回合回复2%最大生命值" },
    { id: 53, name: "森林祝福", type: "wood", rate: 8, description: "每回合回复8点魔法值，每回合回复4%最大生命值" },
    { id: 54, name: "生命之心", type: "wood", rate: 7, description: "每回合回复7点魔法值，治疗效果提升30%" },
    { id: 55, name: "光辉祝福", type: "light", rate: 8, description: "每回合回复8点魔法值，净化所有负面效果并回复生命值" },
    { id: 56, name: "圣光之魂", type: "light", rate: 7, description: "每回合回复7点魔法值，受到治疗效果提升30%" },
    { id: 57, name: "暗影祝福", type: "dark", rate: 9, description: "每回合回复9点魔法值，攻击时回复造成伤害3%的生命值" },
    { id: 58, name: "虚空之心", type: "dark", rate: 10, description: "每回合回复10点魔法值，暴击率提升15%" },
    { id: 59, name: "虚无祝福", type: "none", rate: 11, description: "每回合回复11点魔法值，所有技能无视防御和属性克制" },
    { id: 60, name: "混沌祝福", type: "none", rate: 12, description: "每回合回复12点魔法值，使用技能后有35%概率不消耗魔法值" },
    // 再新增10个回蓝机制
    { id: 61, name: "地狱之心", type: "fire", rate: 11, description: "每回合回复11点魔法值，暴击时回复额外生命值和魔法值" },
    { id: 62, name: "熔岩神魂", type: "fire", rate: 10, description: "每回合回复10点魔法值，受到致命伤害时回复10点魔法值和生命值" },
    { id: 63, name: "海神神力", type: "water", rate: 11, description: "每回合回复11点魔法值，每回合回复4%最大生命值" },
    { id: 64, name: "深海神心", type: "water", rate: 9, description: "每回合回复9点魔法值，暴击伤害提升30%" },
    { id: 65, name: "大地神佑", type: "earth", rate: 10, description: "每回合回复10点魔法值，受到暴击时回复10点魔法值和生命值" },
    { id: 66, name: "岩石神心", type: "earth", rate: 9, description: "每回合回复9点魔法值，每回合回复3%最大生命值和魔法值" },
    { id: 67, name: "森林神佑", type: "wood", rate: 9, description: "每回合回复9点魔法值，每回合回复5%最大生命值" },
    { id: 68, name: "生命神心", type: "wood", rate: 8, description: "每回合回复8点魔法值，治疗效果提升35%" },
    { id: 69, name: "光辉神佑", type: "light", rate: 9, description: "每回合回复9点魔法值，净化所有负面效果并回复生命值和魔法值" },
    { id: 70, name: "圣光神魂", type: "light", rate: 8, description: "每回合回复8点魔法值，受到治疗效果提升35%" },
    { id: 71, name: "暗影神佑", type: "dark", rate: 10, description: "每回合回复10点魔法值，攻击时回复造成伤害4%的生命值" },
    { id: 72, name: "虚空神心", type: "dark", rate: 11, description: "每回合回复11点魔法值，暴击率提升20%" },
    { id: 73, name: "虚无神佑", type: "none", rate: 12, description: "每回合回复12点魔法值，所有技能无视防御和属性克制" },
    { id: 74, name: "混沌神心", type: "none", rate: 13, description: "每回合回复13点魔法值，使用技能后有40%概率不消耗魔法值" }
];

// 内置大招模板
const ultimateTemplates = [
    { id: 1, name: "天火焚城", type: "fire", power: 100, rageCost: 100, description: "召唤天火焚烧一切敌人" },
    { id: 2, name: "海啸", type: "water", power: 90, rageCost: 100, description: "引发巨大海啸淹没敌人" },
    { id: 3, name: "地震", type: "earth", power: 95, rageCost: 100, description: "引发强烈地震震撼敌人" },
    { id: 4, name: "森林之怒", type: "wood", power: 85, rageCost: 100, description: "召唤森林之灵攻击敌人并治愈自己", heal: 50 },
    { id: 5, name: "圣光洗礼", type: "light", power: 90, rageCost: 100, description: "释放纯净圣光，对敌人造成巨大伤害并治愈自己", heal: 30 },
    { id: 6, name: "末日降临", type: "dark", power: 110, rageCost: 100, description: "召唤末日之力，对敌人造成毁灭性打击" },
    { id: 7, name: "雷霆万钧", type: "water", power: 95, rageCost: 100, description: "召唤雷电风暴，对敌人造成多次伤害" },
    { id: 8, name: "火山爆发", type: "fire", power: 105, rageCost: 100, description: "引发火山爆发，对敌人造成巨额伤害并附加燃烧效果" },
    { id: 9, name: "大地守护", type: "earth", power: 0, rageCost: 100, description: "召唤大地守护，免疫所有伤害3回合", shield: 3 },
    { id: 10, name: "生命之树", type: "wood", power: 0, rageCost: 100, description: "召唤生命之树，每回合回复所有队友大量生命值", teamHeal: 40 },
    { id: 11, name: "冰封千里", type: "water", power: 120, rageCost: 100, description: "释放极寒之力，冻结所有敌人并造成巨额伤害" },
    { id: 12, name: "烈焰风暴", type: "fire", power: 110, rageCost: 100, description: "召唤毁灭性烈焰风暴，对所有敌人造成多次伤害" },
    { id: 13, name: "山崩地裂", type: "earth", power: 115, rageCost: 100, description: "引发山崩地裂，对所有敌人造成巨额伤害并附加流血效果" },
    { id: 14, name: "森林复苏", type: "wood", power: 0, rageCost: 100, description: "唤醒森林之力，立即复活所有死亡队友并回复全部生命值", revive: true },
    { id: 15, name: "神圣审判", type: "light", power: 100, rageCost: 100, description: "召唤神圣力量，对所有敌人造成巨额伤害并净化所有负面效果", purge: true },
    { id: 16, name: "深渊降临", type: "dark", power: 125, rageCost: 100, description: "召唤深渊之力，对所有敌人造成毁灭性打击并附加诅咒效果" },
    { id: 17, name: "风暴领域", type: "water", power: 110, rageCost: 100, description: "展开风暴领域，对所有敌人造成巨额伤害并降低其命中率" },
    { id: 18, name: "地狱之门", type: "fire", power: 120, rageCost: 100, description: "打开地狱之门，对所有敌人造成毁灭性打击但会消耗自身生命值", selfDamage: 20 },
    { id: 19, name: "大地之怒", type: "earth", power: 115, rageCost: 100, description: "召唤大地之怒，对所有敌人造成巨额伤害并附加石化效果", stun: 2 },
    { id: 20, name: "自然庇护", type: "wood", power: 0, rageCost: 100, description: "获得自然庇护，免疫所有负面效果并回复所有队友生命值", teamHeal: 30, shield: 2 },
    { id: 21, name: "天堂光辉", type: "light", power: 100, rageCost: 100, description: "释放天堂光辉，对所有敌人造成巨额伤害并复活所有死亡队友", revive: true },
    { id: 22, name: "暗影军团", type: "dark", power: 130, rageCost: 100, description: "召唤暗影军团，对所有敌人造成毁灭性打击并附加多个负面效果" },
    { id: 23, name: "星辰陨落", type: "none", power: 140, rageCost: 100, description: "召唤星辰陨落，无视属性克制对所有敌人造成毁灭性打击" },
    { id: 24, name: "时间静止", type: "none", power: 0, rageCost: 100, description: "静止时间，立即击败所有敌人", instantKill: true },
    { id: 25, name: "空间崩坏", type: "none", power: 150, rageCost: 100, description: "崩坏空间，对所有敌人造成巨额伤害并附加多种负面效果" },
    { id: 26, name: "元素湮灭", type: "none", power: 135, rageCost: 100, description: "湮灭元素，根据敌人属性选择最优攻击方式造成巨额伤害" },
    { id: 27, name: "宇宙重构", type: "none", power: 0, rageCost: 100, description: "重构宇宙，复活所有队友并清除所有负面效果", revive: true, purge: true },
    { id: 28, name: "虚无之境", type: "none", power: 160, rageCost: 100, description: "进入虚无之境，对所有敌人造成毁灭性打击并附加永久诅咒效果" },
    // 新增大招
    { id: 29, name: "炎龙咆哮", type: "fire", power: 145, rageCost: 100, description: "召唤炎龙咆哮，对所有敌人造成毁灭性火焰伤害并附加燃烧效果", dot: 15, dotDuration: 3 },
    { id: 30, name: "熔岩领域", type: "fire", power: 130, rageCost: 100, description: "展开熔岩领域，对所有敌人造成巨额伤害并反弹部分伤害", reflect: 0.3 },
    { id: 31, name: "海神之怒", type: "water", power: 135, rageCost: 100, description: "召唤海神之怒，对所有敌人造成巨额水属性伤害并附加减速效果" },
    { id: 32, name: "冰川纪元", type: "water", power: 125, rageCost: 100, description: "开启冰川纪元，冻结所有敌人并造成巨额伤害", stun: 2 },
    { id: 33, name: "泰山压顶", type: "earth", power: 140, rageCost: 100, description: "召唤泰山之力压顶，对所有敌人造成巨额伤害并附加眩晕效果", stun: 1 },
    { id: 34, name: "大地之心", type: "earth", power: 0, rageCost: 100, description: "激活大地之心，为所有队友提供相当于最大生命值30%的护盾", shield: 0.3 },
    { id: 35, name: "世界树降临", type: "wood", power: 0, rageCost: 100, description: "召唤世界树降临，立即复活所有死亡队友并回复全部生命值，同时持续回复生命值", revive: true, teamHeal: 25, dotDuration: 3 },
    { id: 36, name: "荆棘囚笼", type: "wood", power: 120, rageCost: 100, description: "展开荆棘囚笼，对所有敌人造成巨额伤害并反弹部分伤害", reflect: 0.25 },
    { id: 37, name: "天使军团", type: "light", power: 130, rageCost: 100, description: "召唤天使军团，对所有敌人造成巨额光属性伤害并净化所有负面效果", purge: true },
    { id: 38, name: "光明圣域", type: "light", power: 0, rageCost: 100, description: "创造光明圣域，免疫所有负面效果并持续回复所有队友生命值", teamHeal: 35, shield: 2 },
    { id: 39, name: "恶魔契约", type: "dark", power: 150, rageCost: 100, description: "签订恶魔契约，对所有敌人造成毁灭性暗属性伤害但会消耗自身30%生命值", selfDamage: 30 },
    { id: 40, name: "死亡领域", type: "dark", power: 135, rageCost: 100, description: "展开死亡领域，对所有敌人造成巨额伤害并附加多个负面效果" },
    { id: 41, name: "维度撕裂", type: "none", power: 170, rageCost: 100, description: "撕裂维度，对所有敌人造成毁灭性伤害并无视一切防御", instantKill: true },
    { id: 42, name: "混沌降临", type: "none", power: 155, rageCost: 100, description: "混沌降临，对所有敌人造成巨额伤害并附加所有负面效果" },
    // 再新增大招
    { id: 43, name: "太阳风暴", type: "fire", power: 160, rageCost: 100, description: "召唤太阳风暴，对所有敌人造成毁灭性火焰伤害并附加燃烧和眩晕效果", dot: 20, dotDuration: 2, stun: 1 },
    { id: 44, name: "熔岩之心", type: "fire", power: 140, rageCost: 100, description: "激活熔岩之心，对所有敌人造成巨额伤害并反弹所有攻击", reflect: 0.5 },
    { id: 45, name: "万丈狂澜", type: "water", power: 150, rageCost: 100, description: "掀起万丈狂澜，对所有敌人造成巨额水属性伤害并附加减速和流血效果" },
    { id: 46, name: "绝对零度", type: "water", power: 135, rageCost: 100, description: "释放绝对零度，冻结所有敌人并造成巨额伤害", stun: 3 },
    { id: 47, name: "地动山摇", type: "earth", power: 155, rageCost: 100, description: "引发地动山摇，对所有敌人造成巨额伤害并附加眩晕和流血效果", stun: 1 },
    { id: 48, name: "岩石巨人", type: "earth", power: 0, rageCost: 100, description: "召唤岩石巨人，为所有队友提供相当于最大生命值50%的护盾并反弹伤害", shield: 0.5, reflect: 0.2 },
    { id: 49, name: "生命洪流", type: "wood", power: 0, rageCost: 100, description: "释放生命洪流，立即复活所有死亡队友并回复全部生命值，同时大幅提升治疗效果", revive: true, teamHeal: 50 },
    { id: 50, name: "森林之神", type: "wood", power: 130, rageCost: 100, description: "召唤森林之神，对所有敌人造成巨额伤害并持续回复所有队友生命值", teamHeal: 30, dotDuration: 4 },
    { id: 51, name: "神圣裁决", type: "light", power: 145, rageCost: 100, description: "执行神圣裁决，对所有敌人造成巨额光属性伤害并净化所有负面效果和增益效果", purge: true },
    { id: 52, name: "天堂领域", type: "light", power: 0, rageCost: 100, description: "展开天堂领域，免疫所有伤害和负面效果并持续回复所有队友生命值和魔法值", teamHeal: 25, shield: 3 },
    { id: 53, name: "深渊魔龙", type: "dark", power: 165, rageCost: 100, description: "召唤深渊魔龙，对所有敌人造成毁灭性暗属性伤害并附加诅咒和流血效果" },
    { id: 54, name: "死亡之舞", type: "dark", power: 140, rageCost: 100, description: "跳起死亡之舞，对所有敌人造成巨额伤害并根据造成伤害回复生命值", lifesteal: 0.5 },
    { id: 55, name: "宇宙撕裂", type: "none", power: 180, rageCost: 100, description: "撕裂宇宙，对所有敌人造成毁灭性伤害并无视一切防御和属性克制", instantKill: true },
    { id: 56, name: "混沌风暴", type: "none", power: 165, rageCost: 100, description: "召唤混沌风暴，对所有敌人造成巨额伤害并附加所有负面效果和随机属性攻击" },
    // 再新增5个大招
    { id: 57, name: "地狱烈焰", type: "fire", power: 175, rageCost: 100, description: "释放地狱烈焰，对所有敌人造成毁灭性火焰伤害并附加燃烧、眩晕和流血效果", dot: 25, dotDuration: 3, stun: 1 },
    { id: 58, name: "熔岩神域", type: "fire", power: 155, rageCost: 100, description: "展开熔岩神域，对所有敌人造成巨额伤害并反弹所有攻击且灼烧攻击者", reflect: 0.6 },
    { id: 59, name: "海啸神罚", type: "water", power: 165, rageCost: 100, description: "降下海啸神罚，对所有敌人造成巨额水属性伤害并附加减速、眩晕和流血效果", stun: 2 },
    { id: 60, name: "冰封世界", type: "water", power: 150, rageCost: 100, description: "冰封整个世界，冻结所有敌人并造成巨额伤害", stun: 4 },
    { id: 61, name: "大地神罚", type: "earth", power: 170, rageCost: 100, description: "降下大地神罚，对所有敌人造成巨额伤害并附加眩晕、流血和石化效果", stun: 1 },
    { id: 62, name: "山崩海啸", type: "earth", power: 0, rageCost: 100, description: "引发山崩海啸，为所有队友提供相当于最大生命值70%的护盾并反弹伤害", shield: 0.7, reflect: 0.3 },
    { id: 63, name: "生命神树", type: "wood", power: 0, rageCost: 100, description: "召唤生命神树，立即复活所有死亡队友并回复全部生命值，同时大幅提升治疗效果和持续回复", revive: true, teamHeal: 60, dotDuration: 5 },
    { id: 64, name: "森林之王", type: "wood", power: 145, rageCost: 100, description: "召唤森林之王，对所有敌人造成巨额伤害并持续回复所有队友生命值和魔法值", teamHeal: 35, dotDuration: 5 },
    { id: 65, name: "神圣审判", type: "light", power: 160, rageCost: 100, description: "执行神圣审判，对所有敌人造成巨额光属性伤害并净化所有负面效果和增益效果", purge: true },
    { id: 66, name: "天堂之门", type: "light", power: 0, rageCost: 100, description: "打开天堂之门，免疫所有伤害和负面效果并持续回复所有队友生命值、魔法值和怒气值", teamHeal: 30, shield: 4 },
    { id: 67, name: "深渊之主", type: "dark", power: 180, rageCost: 100, description: "召唤深渊之主，对所有敌人造成毁灭性暗属性伤害并附加诅咒、流血和恐惧效果" },
    { id: 68, name: "死亡领域", type: "dark", power: 155, rageCost: 100, description: "展开死亡领域，对所有敌人造成巨额伤害并根据造成伤害回复生命值", lifesteal: 0.6 },
    { id: 69, name: "宇宙之心", type: "none", power: 195, rageCost: 100, description: "激活宇宙之心，对所有敌人造成毁灭性伤害并无视一切防御和属性克制", instantKill: true },
    { id: 70, name: "混沌神域", type: "none", power: 180, rageCost: 100, description: "展开混沌神域，对所有敌人造成巨额伤害并附加所有负面效果和随机属性攻击" },
    // 再新增10个大招
    { id: 71, name: "地狱神罚", type: "fire", power: 190, rageCost: 100, description: "降下地狱神罚，对所有敌人造成毁灭性火焰伤害并附加燃烧、眩晕、流血和恐惧效果", dot: 30, dotDuration: 4, stun: 2 },
    { id: 72, name: "熔岩神心", type: "fire", power: 170, rageCost: 100, description: "激活熔岩神心，对所有敌人造成巨额伤害并反弹所有攻击且灼烧攻击者", reflect: 0.7 },
    { id: 73, name: "海神之怒", type: "water", power: 180, rageCost: 100, description: "召唤海神之怒，对所有敌人造成巨额水属性伤害并附加减速、眩晕、流血和石化效果", stun: 3 },
    { id: 74, name: "冰封神域", type: "water", power: 165, rageCost: 100, description: "冰封整个神域，冻结所有敌人并造成巨额伤害", stun: 5 },
    { id: 75, name: "大地神怒", type: "earth", power: 185, rageCost: 100, description: "引发大地神怒，对所有敌人造成巨额伤害并附加眩晕、流血、石化和恐惧效果", stun: 2 },
    { id: 76, name: "山崩神罚", type: "earth", power: 0, rageCost: 100, description: "引发山崩神罚，为所有队友提供相当于最大生命值90%的护盾并反弹伤害", shield: 0.9, reflect: 0.4 },
    { id: 77, name: "生命神域", type: "wood", power: 0, rageCost: 100, description: "展开生命神域，立即复活所有死亡队友并回复全部生命值，同时大幅提升治疗效果和持续回复", revive: true, teamHeal: 70, dotDuration: 6 },
    { id: 78, name: "森林之神", type: "wood", power: 160, rageCost: 100, description: "召唤森林之神，对所有敌人造成巨额伤害并持续回复所有队友生命值、魔法值和怒气值", teamHeal: 40, dotDuration: 6 },
    { id: 79, name: "神圣神罚", type: "light", power: 175, rageCost: 100, description: "执行神圣神罚，对所有敌人造成巨额光属性伤害并净化所有负面效果和增益效果", purge: true },
    { id: 80, name: "天堂神域", type: "light", power: 0, rageCost: 100, description: "展开天堂神域，免疫所有伤害和负面效果并持续回复所有队友生命值、魔法值和怒气值", teamHeal: 35, shield: 5 },
    { id: 81, name: "深渊神主", type: "dark", power: 195, rageCost: 100, description: "召唤深渊神主，对所有敌人造成毁灭性暗属性伤害并附加诅咒、流血、恐惧和石化效果" },
    { id: 82, name: "死亡神域", type: "dark", power: 170, rageCost: 100, description: "展开死亡神域，对所有敌人造成巨额伤害并根据造成伤害回复生命值", lifesteal: 0.7 },
    { id: 83, name: "宇宙神心", type: "none", power: 210, rageCost: 100, description: "激活宇宙神心，对所有敌人造成毁灭性伤害并无视一切防御和属性克制", instantKill: true },
    { id: 84, name: "混沌神罚", type: "none", power: 195, rageCost: 100, description: "降下混沌神罚，对所有敌人造成巨额伤害并附加所有负面效果和随机属性攻击" }
];

// 内置角色模板
const characterTemplates = [
    {
        id: 1,
        name: "火焰兽",
        type: "fire",
        maxHealth: 100,
        health: 100,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 25,
        defense: 15,
        skills: [1, 5],
        passives: [4],
        manaRegen: 1,
        ultimates: [1],
        description: "一种生活在火山附近的神奇生物，能够喷射高温火焰。",
        image: "🔥"
    },
    {
        id: 2,
        name: "水精灵",
        type: "water",
        maxHealth: 90,
        health: 90,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 20,
        defense: 20,
        skills: [2, 6],
        passives: [3],
        manaRegen: 2,
        ultimates: [2],
        description: "栖息在深海中的神秘精灵，操控着强大的水元素力量。",
        image: "💧"
    },
    {
        id: 3,
        name: "岩石巨人",
        type: "earth",
        maxHealth: 150,
        health: 150,
        maxMana: 60,
        mana: 60,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 30,
        skills: [3],
        passives: [1],
        manaRegen: 1,
        ultimates: [3],
        description: "由大地孕育而生的岩石生命体，拥有极高的防御力。",
        image: "🗿"
    },
    {
        id: 4,
        name: "森林守护者",
        type: "wood",
        maxHealth: 110,
        health: 110,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 22,
        defense: 18,
        skills: [4],
        passives: [2],
        manaRegen: 1,
        ultimates: [4],
        description: "古老森林的守护者，能够操控植物并治愈伤痛。",
        image: "🌳"
    },
    {
        id: 5,
        name: "光明天使",
        type: "light",
        maxHealth: 100,
        health: 100,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 20,
        defense: 20,
        skills: [7, 9],
        passives: [5],
        manaRegen: 4,
        ultimates: [5],
        description: "来自天堂的使者，掌握着光明的力量，能够治愈盟友并惩戒邪恶。",
        image: "👼"
    },
    {
        id: 6,
        name: "暗影刺客",
        type: "dark",
        maxHealth: 90,
        health: 90,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 35,
        defense: 10,
        skills: [8, 10],
        passives: [6],
        manaRegen: 5,
        ultimates: [6],
        description: "潜伏在阴影中的杀手，擅长暗杀和持续伤害，行动迅速且致命。",
        image: "🗡️"
    },
    {
        id: 7,
        name: "元素大师",
        type: "fire",
        maxHealth: 120,
        health: 120,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 25,
        defense: 20,
        skills: [1, 2, 3],
        passives: [3],
        manaRegen: 2,
        ultimates: [1],
        description: "精通所有元素的魔法师，能够操控多种元素力量进行战斗。",
        image: "🧙"
    },
    {
        id: 8,
        name: "圣龙",
        type: "light",
        maxHealth: 180,
        health: 180,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 25,
        skills: [7, 4],
        passives: [5],
        manaRegen: 4,
        ultimates: [5],
        description: "神圣的巨龙，拥有强大的光明力量和坚固的鳞甲，是传说中的存在。",
        image: "🐉"
    },
    {
        id: 9,
        name: "雷电法师",
        type: "water",
        maxHealth: 95,
        health: 95,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 23,
        defense: 12,
        skills: [11, 2],
        passives: [7],
        manaRegen: 6,
        ultimates: [7],
        description: "掌控雷电之力的法师职业，拥有强大的法术输出和法力回复能力。",
        image: "⚡"
    },
    {
        id: 10,
        name: "熔岩领主",
        type: "fire",
        maxHealth: 140,
        health: 140,
        maxMana: 70,
        mana: 70,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 22,
        skills: [12, 5],
        passives: [8],
        manaRegen: 7,
        ultimates: [8],
        description: "掌控熔岩力量的领主，拥有强大的火系攻击和防御能力。",
        image: "🌋"
    },
    {
        id: 11,
        name: "荆棘德鲁伊",
        type: "wood",
        maxHealth: 120,
        health: 120,
        maxMana: 95,
        mana: 95,
        maxRage: 100,
        rage: 0,
        attack: 24,
        defense: 19,
        skills: [13, 4],
        passives: [10],
        manaRegen: 1,
        ultimates: [10],
        description: "与自然融为一体的大德鲁伊，能够操控荆棘和生命之力。",
        image: "🌿"
    },
    {
        id: 12,
        name: "石像鬼",
        type: "earth",
        maxHealth: 110,
        health: 110,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 28,
        skills: [3, 14],
        passives: [9],
        manaRegen: 1,
        ultimates: [9],
        description: "由岩石构成的飞行生物，拥有强大的防御力和石化能力。",
        image: "🦅"
    },
    {
        id: 13,
        name: "冰霜女王",
        type: "water",
        maxHealth: 100,
        health: 100,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 22,
        defense: 18,
        skills: [17, 11],
        passives: [11],
        manaRegen: 8,
        ultimates: [11],
        description: "掌控极寒之力的女王，能够冻结一切敌人。",
        image: "❄️"
    },
    {
        id: 14,
        name: "地狱炎魔",
        type: "fire",
        maxHealth: 160,
        health: 160,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 35,
        defense: 20,
        skills: [18, 12],
        passives: [12],
        manaRegen: 7,
        ultimates: [12],
        description: "来自地狱的火焰恶魔，拥有毁灭性的火系技能。",
        image: "👹"
    },
    {
        id: 15,
        name: "大地守护神",
        type: "earth",
        maxHealth: 200,
        health: 200,
        maxMana: 70,
        mana: 70,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 35,
        skills: [19, 3],
        passives: [13],
        manaRegen: 9,
        ultimates: [13],
        description: "大地的守护神，拥有无与伦比的防御力和控制能力。",
        image: "🏔️"
    },
    {
        id: 16,
        name: "自然之灵",
        type: "wood",
        maxHealth: 130,
        health: 130,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 26,
        defense: 15,
        skills: [20, 13],
        passives: [14],
        manaRegen: 10,
        ultimates: [14],
        description: "自然的化身，能够治愈盟友并操控植物进行战斗。",
        image: "🧚"
    },
    {
        id: 17,
        name: "风暴领主",
        type: "water",
        maxHealth: 110,
        health: 110,
        maxMana: 150,
        mana: 150,
        maxRage: 100,
        rage: 0,
        attack: 25,
        defense: 15,
        skills: [23, 17],
        passives: [17],
        manaRegen: 13,
        ultimates: [17],
        description: "掌控风暴之力的领主，能够召唤雷电和飓风摧毁敌人。",
        image: "🌪️"
    },
    {
        id: 18,
        name: "烈焰凤凰",
        type: "fire",
        maxHealth: 120,
        health: 120,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 20,
        skills: [24, 18],
        passives: [18],
        manaRegen: 14,
        ultimates: [18],
        description: "浴火重生的神鸟，拥有强大的火焰力量和自我恢复能力。",
        image: "🐦‍🔥"
    },
    {
        id: 19,
        name: "山岳泰坦",
        type: "earth",
        maxHealth: 220,
        health: 220,
        maxMana: 60,
        mana: 60,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 40,
        skills: [25, 19],
        passives: [19],
        manaRegen: 9,
        ultimates: [19],
        description: "古老而强大的泰坦，拥有毁天灭地的力量和坚不可摧的防御。",
        image: "⛰️"
    },
    {
        id: 20,
        name: "生命古树",
        type: "wood",
        maxHealth: 180,
        health: 180,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 20,
        defense: 25,
        skills: [26, 20],
        passives: [20],
        manaRegen: 10,
        ultimates: [20],
        description: "拥有悠久生命的古树，能够治愈盟友并提供强大的保护。",
        image: "🌲"
    },
    {
        id: 21,
        name: "虚空行者",
        type: "none",
        maxHealth: 140,
        health: 140,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 18,
        skills: [29, 30],
        passives: [23],
        manaRegen: 15,
        ultimates: [23],
        description: "来自虚空的神秘存在，掌握着超越元素的力量。",
        image: "🕳️"
    },
    {
        id: 22,
        name: "时间守护者",
        type: "none",
        maxHealth: 130,
        health: 130,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 24,
        defense: 20,
        skills: [31, 30],
        passives: [24],
        manaRegen: 16,
        ultimates: [24],
        description: "掌控时间之力的守护者，能够操纵时间的流速。",
        image: "⏰"
    },
    {
        id: 23,
        name: "空间撕裂者",
        type: "none",
        maxHealth: 150,
        health: 150,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 15,
        skills: [32, 31],
        passives: [25],
        manaRegen: 17,
        ultimates: [25],
        description: "能够撕裂空间的异界生物，拥有毁天灭地的力量。",
        image: "🌀"
    },
    {
        id: 24,
        name: "元素君主",
        type: "none",
        maxHealth: 160,
        health: 160,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 22,
        skills: [29, 32],
        passives: [26],
        manaRegen: 18,
        ultimates: [26],
        description: "元素的君主，掌握着所有元素的终极力量。",
        image: "👑"
    },
    // 新增角色
    {
        id: 25,
        name: "烈焰骑士",
        type: "fire",
        maxHealth: 145,
        health: 145,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 34,
        defense: 24,
        skills: [33, 34],
        passives: [27],
        manaRegen: 19,
        ultimates: [29],
        description: "身披烈焰铠甲的骑士，能够释放强大的火焰攻击并保护自己。",
        image: "🔥⚔️"
    },
    {
        id: 26,
        name: "熔岩法师",
        type: "fire",
        maxHealth: 110,
        health: 110,
        maxMana: 135,
        mana: 135,
        maxRage: 100,
        rage: 0,
        attack: 26,
        defense: 16,
        skills: [12, 33],
        passives: [28],
        manaRegen: 20,
        ultimates: [30],
        description: "专精熔岩魔法的法师，能够操控高温熔岩进行攻击和防护。",
        image: "🧙‍♂️🌋"
    },
    {
        id: 27,
        name: "海神使者",
        type: "water",
        maxHealth: 125,
        health: 125,
        maxMana: 125,
        mana: 125,
        maxRage: 100,
        rage: 0,
        attack: 27,
        defense: 22,
        skills: [35, 36],
        passives: [29],
        manaRegen: 21,
        ultimates: [31],
        description: "海神的使者，能够操控潮汐和寒冰的力量。",
        image: "🧜‍♀️🌊"
    },
    {
        id: 28,
        name: "冰霜法师",
        type: "water",
        maxHealth: 105,
        health: 105,
        maxMana: 145,
        mana: 145,
        maxRage: 100,
        rage: 0,
        attack: 24,
        defense: 18,
        skills: [17, 35],
        passives: [30],
        manaRegen: 22,
        ultimates: [32],
        description: "掌控冰霜之力的法师，能够冻结敌人并保护自己。",
        image: "🧙‍♂️❄️"
    },
    {
        id: 29,
        name: "山岭守护者",
        type: "earth",
        maxHealth: 190,
        health: 190,
        maxMana: 75,
        mana: 75,
        maxRage: 100,
        rage: 0,
        attack: 31,
        defense: 38,
        skills: [37, 38],
        passives: [31],
        manaRegen: 23,
        ultimates: [33],
        description: "山岭的守护者，拥有坚不可摧的防御力和强大的大地之力。",
        image: "⛰️🛡️"
    },
    {
        id: 30,
        name: "岩石法师",
        type: "earth",
        maxHealth: 135,
        health: 135,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 29,
        defense: 28,
        skills: [3, 37],
        passives: [32],
        manaRegen: 24,
        ultimates: [34],
        description: "能够操控岩石的法师，可以召唤岩石傀儡协助战斗。",
        image: "🧙‍♂️🪨"
    },
    {
        id: 31,
        name: "森林贤者",
        type: "wood",
        maxHealth: 140,
        health: 140,
        maxMana: 115,
        mana: 115,
        maxRage: 100,
        rage: 0,
        attack: 25,
        defense: 23,
        skills: [39, 40],
        passives: [33],
        manaRegen: 25,
        ultimates: [35],
        description: "古老森林的贤者，能够操控植物并为队友提供持续治疗。",
        image: "🧙‍♀️🌳"
    },
    {
        id: 32,
        name: "荆棘女王",
        type: "wood",
        maxHealth: 120,
        health: 120,
        maxMana: 105,
        mana: 105,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 20,
        skills: [13, 39],
        passives: [34],
        manaRegen: 26,
        ultimates: [36],
        description: "掌控荆棘之力的女王，能够束缚敌人并反弹伤害。",
        image: "👑🌿"
    },
    {
        id: 33,
        name: "光辉骑士",
        type: "light",
        maxHealth: 130,
        health: 130,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 27,
        defense: 25,
        skills: [41, 42],
        passives: [35],
        manaRegen: 27,
        ultimates: [37],
        description: "身披光辉铠甲的骑士，能够驱散邪恶并保护队友。",
        image: "⚔️✨"
    },
    {
        id: 34,
        name: "圣光祭司",
        type: "light",
        maxHealth: 115,
        health: 115,
        maxMana: 135,
        mana: 135,
        maxRage: 100,
        rage: 0,
        attack: 22,
        defense: 22,
        skills: [7, 41],
        passives: [36],
        manaRegen: 28,
        ultimates: [38],
        description: "侍奉光明的祭司，能够释放圣光治愈队友并净化邪恶。",
        image: "⛪🌟"
    },
    {
        id: 35,
        name: "暗影领主",
        type: "dark",
        maxHealth: 125,
        health: 125,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 33,
        defense: 18,
        skills: [43, 44],
        passives: [37],
        manaRegen: 29,
        ultimates: [39],
        description: "暗影的领主，能够束缚敌人并汲取生命力量。",
        image: "🧛‍♂️🌑"
    },
    {
        id: 36,
        name: "恐惧魔王",
        type: "dark",
        maxHealth: 110,
        health: 110,
        maxMana: 125,
        mana: 125,
        maxRage: 100,
        rage: 0,
        attack: 31,
        defense: 15,
        skills: [10, 43],
        passives: [38],
        manaRegen: 30,
        ultimates: [40],
        description: "能够散播恐惧的魔王，可以削弱敌人的战斗力。",
        image: "👹💥"
    },
    {
        id: 37,
        name: "虚无行者",
        type: "none",
        maxHealth: 155,
        health: 155,
        maxMana: 135,
        mana: 135,
        maxRage: 100,
        rage: 0,
        attack: 33,
        defense: 23,
        skills: [45, 46],
        passives: [39],
        manaRegen: 31,
        ultimates: [41],
        description: "来自虚无的行者，掌握着混沌的力量。",
        image: "🌀🕳️"
    },
    {
        id: 38,
        name: "混沌法师",
        type: "none",
        maxHealth: 135,
        health: 135,
        maxMana: 150,
        mana: 150,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 20,
        skills: [29, 45],
        passives: [40],
        manaRegen: 32,
        ultimates: [42],
        description: "掌控混沌之力的法师，能够释放无视一切的攻击。",
        image: "🧙‍♂️🌪️"
    },
    // 再新增角色
    {
        id: 39,
        name: "烈焰帝王",
        type: "fire",
        maxHealth: 160,
        health: 160,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 36,
        defense: 26,
        skills: [47, 48],
        passives: [41],
        manaRegen: 33,
        ultimates: [43],
        description: "火焰的帝王，掌控着最纯粹的烈焰之力，能够焚烧一切敌人。",
        image: "🔥👑"
    },
    {
        id: 40,
        name: "熔岩巨人",
        type: "fire",
        maxHealth: 180,
        health: 180,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 32,
        skills: [24, 47],
        passives: [42],
        manaRegen: 34,
        ultimates: [44],
        description: "由纯粹熔岩构成的巨人，拥有强大的防御力和毁灭性的火焰攻击。",
        image: "🌋🗿"
    },
    {
        id: 41,
        name: "海神",
        type: "water",
        maxHealth: 150,
        health: 150,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 29,
        defense: 24,
        skills: [49, 50],
        passives: [43],
        manaRegen: 35,
        ultimates: [45],
        description: "海洋的统治者，掌控着滔天洪水和极寒冰霜的力量。",
        image: "🌊❄️"
    },
    {
        id: 42,
        name: "冰霜巨龙",
        type: "water",
        maxHealth: 170,
        health: 170,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 31,
        defense: 28,
        skills: [17, 50],
        passives: [44],
        manaRegen: 36,
        ultimates: [46],
        description: "栖息在极地的巨龙，能够释放绝对零度冻结一切敌人。",
        image: "🐉❄️"
    },
    {
        id: 43,
        name: "大地之王",
        type: "earth",
        maxHealth: 210,
        health: 210,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 34,
        defense: 42,
        skills: [51, 52],
        passives: [45],
        manaRegen: 37,
        ultimates: [47],
        description: "大地的王者，拥有坚不可摧的防御力和震撼天地的力量。",
        image: "🏔️👑"
    },
    {
        id: 44,
        name: "钻石傀儡",
        type: "earth",
        maxHealth: 190,
        health: 190,
        maxMana: 70,
        mana: 70,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 45,
        skills: [3, 51],
        passives: [46],
        manaRegen: 38,
        ultimates: [48],
        description: "由纯净钻石构成的傀儡，拥有无与伦比的防御力和反弹伤害的能力。",
        image: "💎傀️"
    },
    {
        id: 45,
        name: "世界树守护者",
        type: "wood",
        maxHealth: 160,
        health: 160,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 26,
        defense: 26,
        skills: [53, 54],
        passives: [47],
        manaRegen: 39,
        ultimates: [49],
        description: "世界树的守护者，拥有强大的生命力和治愈能力。",
        image: "🌳🛡️"
    },
    {
        id: 46,
        name: "自然女神",
        type: "wood",
        maxHealth: 140,
        health: 140,
        maxMana: 150,
        mana: 150,
        maxRage: 100,
        rage: 0,
        attack: 24,
        defense: 22,
        skills: [20, 53],
        passives: [48],
        manaRegen: 40,
        ultimates: [50],
        description: "自然的女神，能够操控森林之力治愈盟友并攻击敌人。",
        image: "🧚‍♀️🍃"
    },
    {
        id: 47,
        name: "正义天使",
        type: "light",
        maxHealth: 145,
        health: 145,
        maxMana: 135,
        mana: 135,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 28,
        skills: [55, 56],
        passives: [49],
        manaRegen: 41,
        ultimates: [51],
        description: "正义的化身，拥有强大的光属性力量和净化邪恶的能力。",
        image: "😇⚔️"
    },
    {
        id: 48,
        name: "光明之神",
        type: "light",
        maxHealth: 160,
        health: 160,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 26,
        defense: 30,
        skills: [7, 55],
        passives: [50],
        manaRegen: 42,
        ultimates: [52],
        description: "光明的神祇，能够创造天堂领域保护所有队友。",
        image: "🌞🛡️"
    },
    {
        id: 49,
        name: "深渊魔龙",
        type: "dark",
        maxHealth: 170,
        health: 170,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 22,
        skills: [57, 58],
        passives: [51],
        manaRegen: 43,
        ultimates: [53],
        description: "来自深渊的魔龙，拥有毁灭性的暗属性力量和诅咒能力。",
        image: "🐉🌑"
    },
    {
        id: 50,
        name: "死神",
        type: "dark",
        maxHealth: 150,
        health: 150,
        maxMana: 125,
        mana: 125,
        maxRage: 100,
        rage: 0,
        attack: 35,
        defense: 20,
        skills: [10, 57],
        passives: [52],
        manaRegen: 44,
        ultimates: [54],
        description: "死亡的化身，能够汲取敌人生命值并跳起死亡之舞。",
        image: "💀镰️"
    },
    {
        id: 51,
        name: "宇宙之主",
        type: "none",
        maxHealth: 180,
        health: 180,
        maxMana: 160,
        mana: 160,
        maxRage: 100,
        rage: 0,
        attack: 36,
        defense: 28,
        skills: [59, 60],
        passives: [53],
        manaRegen: 45,
        ultimates: [55],
        description: "宇宙的主宰，掌握着撕裂虚空和扭曲维度的力量。",
        image: "🌌👑"
    },
    {
        id: 52,
        name: "混沌之神",
        type: "none",
        maxHealth: 170,
        health: 170,
        maxMana: 170,
        mana: 170,
        maxRage: 100,
        rage: 0,
        attack: 34,
        defense: 26,
        skills: [29, 59],
        passives: [54],
        manaRegen: 46,
        ultimates: [56],
        description: "混沌的神祇，能够召唤混沌风暴摧毁一切敌人。",
        image: "🌪️👑"
    },
    // 再新增5个角色
    {
        id: 53,
        name: "地狱领主",
        type: "fire",
        maxHealth: 190,
        health: 190,
        maxMana: 110,
        mana: 110,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 28,
        skills: [61, 62],
        passives: [55],
        manaRegen: 47,
        ultimates: [57],
        description: "地狱的统治者，掌控着最纯粹的地狱之火，能够焚烧一切敌人。",
        image: "🔥👹"
    },
    {
        id: 54,
        name: "熔岩之心",
        type: "fire",
        maxHealth: 200,
        health: 200,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 35,
        defense: 35,
        skills: [33, 61],
        passives: [56],
        manaRegen: 48,
        ultimates: [58],
        description: "由纯粹熔岩核心构成的存在，拥有强大的防御力和毁灭性的火焰攻击。",
        image: "🌋❤️"
    },
    {
        id: 55,
        name: "海神王",
        type: "water",
        maxHealth: 170,
        health: 170,
        maxMana: 150,
        mana: 150,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 26,
        skills: [63, 64],
        passives: [57],
        manaRegen: 49,
        ultimates: [59],
        description: "海洋的王者，掌控着滔天洪水和极寒冰霜的终极力量。",
        image: "🌊👑"
    },
    {
        id: 56,
        name: "深海巨兽",
        type: "water",
        maxHealth: 180,
        health: 180,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 30,
        skills: [49, 63],
        passives: [58],
        manaRegen: 50,
        ultimates: [60],
        description: "栖息在深海最深处的巨兽，能够释放绝对零度冻结一切敌人。",
        image: "🦑❄️"
    },
    {
        id: 57,
        name: "大地神王",
        type: "earth",
        maxHealth: 230,
        health: 230,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 36,
        defense: 45,
        skills: [65, 66],
        passives: [59],
        manaRegen: 51,
        ultimates: [61],
        description: "大地的神王，拥有坚不可摧的防御力和震撼天地的终极力量。",
        image: "🏔️👑"
    },
    {
        id: 58,
        name: "钻石守护神",
        type: "earth",
        maxHealth: 210,
        health: 210,
        maxMana: 80,
        mana: 80,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 48,
        skills: [51, 65],
        passives: [60],
        manaRegen: 52,
        ultimates: [62],
        description: "由纯净钻石构成的守护神，拥有无与伦比的防御力和反弹伤害的能力。",
        image: "💎🛡️"
    },
    {
        id: 59,
        name: "世界树之神",
        type: "wood",
        maxHealth: 180,
        health: 180,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 28,
        skills: [67, 68],
        passives: [61],
        manaRegen: 53,
        ultimates: [63],
        description: "世界树的神祇，拥有强大的生命力和治愈能力。",
        image: "🌳❤️"
    },
    {
        id: 60,
        name: "自然之神",
        type: "wood",
        maxHealth: 160,
        health: 160,
        maxMana: 160,
        mana: 160,
        maxRage: 100,
        rage: 0,
        attack: 26,
        defense: 24,
        skills: [53, 67],
        passives: [62],
        manaRegen: 54,
        ultimates: [64],
        description: "自然的神祇，能够操控森林之力治愈盟友并攻击敌人。",
        image: "🍃👑"
    },
    {
        id: 61,
        name: "正义之神",
        type: "light",
        maxHealth: 165,
        health: 165,
        maxMana: 145,
        mana: 145,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 30,
        skills: [69, 70],
        passives: [63],
        manaRegen: 55,
        ultimates: [65],
        description: "正义的神祇，拥有强大的光属性力量和净化邪恶的终极能力。",
        image: "😇⚔️"
    },
    {
        id: 62,
        name: "光明帝王",
        type: "light",
        maxHealth: 180,
        health: 180,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 32,
        skills: [55, 69],
        passives: [64],
        manaRegen: 56,
        ultimates: [66],
        description: "光明的帝王，能够创造天堂之门保护所有队友。",
        image: "🌞👑"
    },
    {
        id: 63,
        name: "深渊之主",
        type: "dark",
        maxHealth: 190,
        health: 190,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 40,
        defense: 24,
        skills: [71, 72],
        passives: [65],
        manaRegen: 57,
        ultimates: [67],
        description: "深渊的主宰，拥有毁灭性的暗属性终极力量和诅咒能力。",
        image: "🐉🌑"
    },
    {
        id: 64,
        name: "死亡之神",
        type: "dark",
        maxHealth: 170,
        health: 170,
        maxMana: 135,
        mana: 135,
        maxRage: 100,
        rage: 0,
        attack: 37,
        defense: 22,
        skills: [57, 71],
        passives: [66],
        manaRegen: 58,
        ultimates: [68],
        description: "死亡的神祇，能够汲取敌人生命值并释放恐惧之云。",
        image: "💀👑"
    },
    {
        id: 65,
        name: "宇宙帝王",
        type: "none",
        maxHealth: 200,
        health: 200,
        maxMana: 170,
        mana: 170,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 30,
        skills: [73, 74],
        passives: [67],
        manaRegen: 59,
        ultimates: [69],
        description: "宇宙的帝王，掌握着撕裂虚空和扭曲维度的终极力量。",
        image: "🌌👑"
    },
    {
        id: 66,
        name: "混沌帝王",
        type: "none",
        maxHealth: 190,
        health: 190,
        maxMana: 180,
        mana: 180,
        maxRage: 100,
        rage: 0,
        attack: 36,
        defense: 28,
        skills: [59, 73],
        passives: [68],
        manaRegen: 60,
        ultimates: [70],
        description: "混沌的帝王，能够展开混沌神域摧毁一切敌人。",
        image: "🌪️👑"
    },
    // 再新增10个角色
    {
        id: 67,
        name: "地狱帝王",
        type: "fire",
        maxHealth: 210,
        health: 210,
        maxMana: 120,
        mana: 120,
        maxRage: 100,
        rage: 0,
        attack: 40,
        defense: 30,
        skills: [75, 76],
        passives: [69],
        manaRegen: 61,
        ultimates: [71],
        description: "地狱的帝王，掌控着最纯粹的地狱之火，能够焚烧一切敌人。",
        image: "🔥👹"
    },
    {
        id: 68,
        name: "熔岩神心",
        type: "fire",
        maxHealth: 220,
        health: 220,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 38,
        skills: [61, 75],
        passives: [70],
        manaRegen: 62,
        ultimates: [72],
        description: "由纯粹熔岩神心构成的存在，拥有强大的防御力和毁灭性的火焰攻击。",
        image: "🌋❤️"
    },
    {
        id: 69,
        name: "海神帝王",
        type: "water",
        maxHealth: 190,
        health: 190,
        maxMana: 160,
        mana: 160,
        maxRage: 100,
        rage: 0,
        attack: 34,
        defense: 28,
        skills: [77, 78],
        passives: [71],
        manaRegen: 63,
        ultimates: [73],
        description: "海洋的帝王，掌控着滔天洪水和极寒冰霜的神级力量。",
        image: "🌊👑"
    },
    {
        id: 70,
        name: "深海神兽",
        type: "water",
        maxHealth: 200,
        health: 200,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 32,
        skills: [63, 77],
        passives: [72],
        manaRegen: 64,
        ultimates: [74],
        description: "栖息在深海最深处的神兽，能够释放绝对零度冻结一切敌人。",
        image: "🦑❄️"
    },
    {
        id: 71,
        name: "大地神帝",
        type: "earth",
        maxHealth: 250,
        health: 250,
        maxMana: 100,
        mana: 100,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 48,
        skills: [79, 80],
        passives: [73],
        manaRegen: 65,
        ultimates: [75],
        description: "大地的神帝，拥有坚不可摧的防御力和震撼天地的神级力量。",
        image: "🏔️👑"
    },
    {
        id: 72,
        name: "钻石神盾",
        type: "earth",
        maxHealth: 230,
        health: 230,
        maxMana: 90,
        mana: 90,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 50,
        skills: [65, 79],
        passives: [74],
        manaRegen: 66,
        ultimates: [76],
        description: "由纯净钻石构成的神盾，拥有无与伦比的防御力和反弹伤害的能力。",
        image: "💎🛡️"
    },
    {
        id: 73,
        name: "世界树神",
        type: "wood",
        maxHealth: 200,
        health: 200,
        maxMana: 150,
        mana: 150,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 30,
        skills: [81, 82],
        passives: [75],
        manaRegen: 67,
        ultimates: [77],
        description: "世界树的神祇，拥有强大的生命力和治愈能力。",
        image: "🌳❤️"
    },
    {
        id: 74,
        name: "自然神帝",
        type: "wood",
        maxHealth: 180,
        health: 180,
        maxMana: 170,
        mana: 170,
        maxRage: 100,
        rage: 0,
        attack: 28,
        defense: 26,
        skills: [67, 81],
        passives: [76],
        manaRegen: 68,
        ultimates: [78],
        description: "自然的神帝，能够操控森林之力治愈盟友并攻击敌人。",
        image: "🍃👑"
    },
    {
        id: 75,
        name: "正义神帝",
        type: "light",
        maxHealth: 185,
        health: 185,
        maxMana: 155,
        mana: 155,
        maxRage: 100,
        rage: 0,
        attack: 32,
        defense: 32,
        skills: [83, 84],
        passives: [77],
        manaRegen: 69,
        ultimates: [79],
        description: "正义的神帝，拥有强大的光属性力量和净化邪恶的神级能力。",
        image: "😇⚔️"
    },
    {
        id: 76,
        name: "光明神帝",
        type: "light",
        maxHealth: 200,
        health: 200,
        maxMana: 140,
        mana: 140,
        maxRage: 100,
        rage: 0,
        attack: 30,
        defense: 34,
        skills: [69, 83],
        passives: [78],
        manaRegen: 70,
        ultimates: [80],
        description: "光明的神帝，能够创造天堂神域保护所有队友。",
        image: "🌞👑"
    },
    {
        id: 77,
        name: "深渊神帝",
        type: "dark",
        maxHealth: 210,
        health: 210,
        maxMana: 130,
        mana: 130,
        maxRage: 100,
        rage: 0,
        attack: 42,
        defense: 26,
        skills: [85, 86],
        passives: [79],
        manaRegen: 71,
        ultimates: [81],
        description: "深渊的神帝，拥有毁灭性的暗属性神级力量和诅咒能力。",
        image: "🐉🌑"
    },
    {
        id: 78,
        name: "死亡神帝",
        type: "dark",
        maxHealth: 190,
        health: 190,
        maxMana: 145,
        mana: 145,
        maxRage: 100,
        rage: 0,
        attack: 39,
        defense: 24,
        skills: [71, 85],
        passives: [80],
        manaRegen: 72,
        ultimates: [82],
        description: "死亡的神帝，能够汲取敌人生命值并释放恐惧领域。",
        image: "💀👑"
    },
    {
        id: 79,
        name: "宇宙神帝",
        type: "none",
        maxHealth: 220,
        health: 220,
        maxMana: 180,
        mana: 180,
        maxRage: 100,
        rage: 0,
        attack: 40,
        defense: 32,
        skills: [87, 88],
        passives: [81],
        manaRegen: 73,
        ultimates: [83],
        description: "宇宙的神帝，掌握着撕裂虚空和扭曲维度的神级力量。",
        image: "🌌👑"
    },
    {
        id: 80,
        name: "混沌神帝",
        type: "none",
        maxHealth: 210,
        health: 210,
        maxMana: 190,
        mana: 190,
        maxRage: 100,
        rage: 0,
        attack: 38,
        defense: 30,
        skills: [73, 87],
        passives: [82],
        manaRegen: 74,
        ultimates: [84],
        description: "混沌的神帝，能够展开混沌神罚摧毁一切敌人。",
        image: "🌪️👑"
    }
];

// 游戏状态
const gameState = {
    playerTeam: [],
    playerCharacters: [...characterTemplates],
    shopItems: [...skillTemplates],
    currentBattle: null,
    level: 1
};

// 工具函数
function calculateDamage(attacker, defender, skill) {
    // 基础伤害计算
    let damage = (attacker.attack + skill.power) - defender.defense;
    damage = Math.max(1, damage); // 确保至少造成1点伤害
    
    // 属性克制计算（"none"属性技能无视克制关系）
    if (skill.type !== "none") {
        const effectiveness = typeEffectiveness[skill.type][defender.type] || 1;
        damage = Math.floor(damage * effectiveness);
    }
    
    // 额外伤害加成（如净化之光对暗属性敌人）
    if (skill.bonus && defender.type === skill.bonus.type) {
        damage = Math.floor(damage * skill.bonus.multiplier);
    }
    
    return damage;
}

function getTypeColor(type) {
    const colors = {
        fire: "#ff5555",
        water: "#5555ff",
        earth: "#8b4513",
        wood: "#228b22",
        light: "#ffff00",
        dark: "#4b0082",
        none: "#ffffff"
    };
    return colors[type] || "#ffffff";
}

function formatType(type) {
    const names = {
        fire: "火",
        water: "水",
        earth: "土",
        wood: "木",
        light: "光",
        dark: "暗",
        none: "无"
    };
    return names[type] || type;
}

// 页面加载完成后初始化
document.addEventListener('DOMContentLoaded', function() {
    console.log("游戏已加载");
    // 可以在这里添加首页特定的初始化代码
});

// 导出函数供其他页面使用
window.game = {
    typeEffectiveness,
    skillTemplates,
    passiveTemplates,
    manaRegenTemplates,
    ultimateTemplates,
    characterTemplates,
    gameState,
    calculateDamage,
    getTypeColor,
    formatType
};